let arr = [1,2,2,3,4,5,6]
const set = new  Set(arr)
// console.log(set.add(7))
// console.log(set.delete(6))
// console.log(set.size)
// //console.log(set.clear())
// console.log(set)
// console.log(set.has(7))
//
// console.log(set.keys().next())
// console.log(set.values().next())
// console.log(set.entries().next())
// console.log(typeof set)
// const map = new Map([[1,22],[2,33]])
// console.log(...map)
// console.log(map.set(3,33))
// console.log(map.get(1))
// console.log(map.delete(3))
// console.log(map.has(2))
// console.log(map.keys())
// console.log(map.values())
// console.log(map.entries())
// map.forEach((v, k, m) => console.log(v, k , m))
